modLoader = "javafml"
license = "MIT license"
loaderVersion = "[32,)"
#issueTrackerURL=""

[[mods]]
modId = "ceiling_carpets"
version = "0.0.1"
displayName = "Ceiling Carpets"
#updateJSONURL=""
authors = "Grimmauld"
description = '''
Put carpets on ceilings'''

[[dependencies.ceiling_carpets]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ceiling_carpets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.1]"
ordering = "NONE"
side = "BOTH"